# Generated by Django 6.1 on 2026-08-23 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='founditem',
            name='location_found',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
